---
title: Họ Ericaceae
subtitle: Họ **Ericaceae** gồm Arbutus, Calluna, Chimaphila, Epigaea, Gaultheria, Kalmia, Leucothoe, Lyonia, Moneses, Monotropa, Pieris, Pyrola, Rhododendron, Vaccinium chi và 30 loài  được sử dụng ở 21vùng lãnh thổ điều trị 27chứng và bệnh.
description: Họ **Ericaceae** gồm14 chi và 30loài đã ghi nhận sử dụng làm thuốc tại 21 vùng và lãnh thổ. Thống kê cho thầy các loài thuộc họ này có thể điều trị các chứng và bệnh phổ biến nhất gồm thuốc lợi tiểu (7 loài), chất độc (6 loài), chất khử trùng (5 loài), chất làm se (4 loài), ma túy (3 loài) . 05 loài thực vật gồm **Chimaphila umbellata* (6 chứng và bệnh), *Pyrola rotundifolia* (6 chứng và bệnh), *Calluna vulgaris* (3 chứng và bệnh), *Gaultheria procumbens* (3 chứng và bệnh), *Monotropa uniflora* (3 chứng và bệnh)* được xem là sử dụng điều trị nhiều chứng và bệnh nhất. Trong đó, các loài phân lập và xác định được nhiều thành phần nhất gồm *Vaccinium myrtillus* ( 135 hoạt chất), *Pieris japonica* ( 86 hoạt chất), *Rhododendron molle* ( 77 hoạt chất), *Arbutus unedo* ( 73 hoạt chất), *Calluna vulgaris* ( 65 hoạt chất). Loài dược liệu quan trọng thuộc họ này là *Vaccinium myrtillus*
author: "TS. Hoàng Lê Sơn"
image: https://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=f9ba878b-6cf3-4427-aad5-eb4db2d4c0dc
toc: true
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
    include-in-header:
      - text: |
            <style>
                .group-title { font-size: 20px; font-weight: bold; margin-top: 30px; }
                .grid-container { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 20px; }
                .molecule-box { text-align: center; }
                canvas { border: 1px solid #ccc; }
                .mol-name { margin-top: 5px; font-weight: bold; font-size: 14px; }
            </style>
lightbox: auto
fig-cap-location: bottom
categories: ['Dược dân tộc']
listing:
  - id: Ericaceae
    contents: Ericaceae/*.qmd
    sort: "subtitle"
    type: table
    fields: [image, title, subtitle, description]
---

## 1.Tổng quan về thực vật

Họ Ericaceae có tổng cộng 14  chi và 30 loài. 

::: {.table caption="Bảng các loài được sử dụng làm thuốc từ họ Ericaceae"}

| <RowID>   | genus_GIBF   | species_GIBF                                                                                                                                                                                                                                                                                                                   |   Count |
|-----------|--------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
| Row12     | Rhododendron | Rhododendron anthopogon, Rhododendron arboreum, Rhododendron barbatum, Rhododendron campanulatum, Rhododendron falconeri, Rhododendron ferrugineum, Rhododendron indicum, Rhododendron japonicum, Rhododendron lepidotum, Rhododendron japonoheptamerum, Rhododendron molle, Rhododendron ponticum, Rhododendron groenlandicum |      13 |
| Row13     | Vaccinium    | Vaccinium arboreum, Vaccinium myrtillus, Vaccinium uliginosum                                                                                                                                                                                                                                                                  |       3 |
| Row10     | Pieris       | Pieris formosa, Pieris japonica                                                                                                                                                                                                                                                                                                |       2 |
| Row11     | Pyrola       | Pyrola japonica, Pyrola rotundifolia                                                                                                                                                                                                                                                                                           |       2 |
| Row0      | Arbutus      | Arbutus unedo                                                                                                                                                                                                                                                                                                                  |       1 |
| Row1      | Calluna      | Calluna vulgaris                                                                                                                                                                                                                                                                                                               |       1 |
| Row2      | Chimaphila   | Chimaphila umbellata                                                                                                                                                                                                                                                                                                           |       1 |
| Row3      | Epigaea      | Epigaea repens                                                                                                                                                                                                                                                                                                                 |       1 |
| Row4      | Gaultheria   | Gaultheria procumbens                                                                                                                                                                                                                                                                                                          |       1 |
| Row5      | Kalmia       | Kalmia latifolia                                                                                                                                                                                                                                                                                                               |       1 |
| Row6      | Leucothoe    | Leucothoe grayana                                                                                                                                                                                                                                                                                                              |       1 |
| Row7      | Lyonia       | Lyonia ovalifolia                                                                                                                                                                                                                                                                                                              |       1 |
| Row8      | Moneses      | Moneses uniflora                                                                                                                                                                                                                                                                                                               |       1 |
| Row9      | Monotropa    | Monotropa uniflora                                                                                                                                                                                                                                                                                                             |       1 |

:::

Phân bố họ trên thế giới: France, Germany, Spain, Montenegro, Portugal, Algeria, Croatia, Italy, New Zealand, Albania, Greece, Morocco, Australia, Türkiye, United States of America, Poland, Russian Federation, Sweden, United Kingdom of Great Britain and Northern Ireland, Canada, Netherlands, Denmark, Austria, Ireland, Belgium, Mexico, Estonia, Czechia, Belarus, Ukraine, Latvia, Japan, Nepal, India, China, Chinese Taipei, Bhutan, nan, North Macedonia, Switzerland, Slovenia, Slovakia, Finland, Norway, Romania, Nicaragua, South Africa, Viet Nam, Korea, Republic of, Luxembourg, Lithuania, Pakistan, Thailand, Sri Lanka, unknown or invalid, Bangladesh, Singapore, Andorra, Colombia, El Salvador, Guatemala, Brazil, Madagascar, Chile, Panama, Fiji, Georgia, Åland Islands, Iceland, Greenland



<div id="map-leo" style="width: 100%; height: 600px;"></div>

<script src="https://cdn.plot.ly/plotly-3.1.0.min.js"></script>
<script>
const data = {
  title: "Bản đồ phân bố: Ericaceae",
  iso3_codes: ['VNM', 'NOR', 'NIC', 'MEX', 'ZAF', 'BTN', 'CHN', 'FRA', 'THA', 'UKR', 'COL', 'LVA', 'MKD', 'EST', 'BEL', 'LTU', 'ROU', 'GEO', 'BRA', 'AUT', 'GRC', 'AND', 'NPL', 'MDG', 'IRL', 'POL', 'CAN', 'SGP', 'DNK', 'IND', 'FIN', 'ITA', 'AUS', 'BLR', 'HRV', 'LKA', 'CHL', 'FJI', 'PAK', 'MAR', 'RUS', 'SVN', 'ALB', 'ISL', 'PRT', 'BGD', 'DZA', 'GBR', 'GRL', 'SVK', 'ESP', 'GTM', 'CHE', 'TUR', 'SLV', 'CZE', 'NZL', 'USA', 'DEU', 'LUX', 'ALA', 'JPN', 'NLD', 'PAN', 'MNE', 'SWE'],
  color: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
};
const trace = {
  type: "choropleth",
  locationmode: "ISO-3",
  locations: data.iso3_codes,
  z: data.color,
  colorscale: [[0, "#EAEAEA"], [1, "#FFB6C1"]],
  zmin: 0,
  zmax: 1,
  showscale: false
};
const layout = {
  title: {
    text: data.title,
    font: { size: 20 }
  },
  geo: {
    projection: { type: "natural earth" },
    showland: true,
    landcolor: "#EAEAEA",
    showcountries: true
  },
  margin: { l: 0, r: 0, t: 40, b: 0 }
};
Plotly.newPlot("map-leo", [trace], layout);
</script>


## 2. Tổng quan về thành phần hóa học

Từ **họ Ericaceae** có tổng cộng 14  chi và 30 loài.đã phân lập và xác định được 954 hoạt chất từ một số nhóm chính Statistic_Group_Compound. Phân tích sâu hơn về thành phần hóa học giữa các nhóm chúng tôi đề xuất hai hướng tiếp cận sau.

### 2.1 Hợp chất tìm thấy nhiều nhất trong họ Ericaceae

Sau khi tải dữ liệu từ Lotus, các hợp chất sẽ được thống kê lại xem đâu là hoạt chất có tần số xuất hiện trong các loài nhiều nhất. 
<div class="group-title">"Hoạt chất phổ biến trong họ"</div>\n<div class="grid-container">" <div class="molecule-box"> <canvas id="canvas_Row0" width="150" height="150"></canvas> <div class="mol-name">LTS0204616</div></div> <div class="molecule-box"> <canvas id="canvas_Row1" width="150" height="150"></canvas> <div class="mol-name">LTS0071224</div></div> <div class="molecule-box"> <canvas id="canvas_Row2" width="150" height="150"></canvas> <div class="mol-name">LTS0250838</div></div> <div class="molecule-box"> <canvas id="canvas_Row3" width="150" height="150"></canvas> <div class="mol-name">LTS0089156</div></div> <div class="molecule-box"> <canvas id="canvas_Row4" width="150" height="150"></canvas> <div class="mol-name">LTS0166564</div></div></div>

### 2.2 Tìm kiếm sự tương đồng

::: {.callout-note title = "Find Maximum Common Substructure" }
        
Thuật toán FMCS (Find Maximum Common Substructure) là một phương pháp được sử dụng để tìm ra cấu trúc chung nhiều nhất (MCS) trong một tập hợp các cấu trúc hóa học. Các bước của thuật toán gồm:
        
- Chọn một cấu trúc hóa học là cấu trúc để tạo truy vấn, còn các cấu trúc khác là mục tiêu.
- Chia nhỏ cấu trúc để tạo truy vấn thành cấu trúc nhỏ hơn dạng chuỗi SMARTS.
- Kiểm tra chuỗi SMARTS trong các cấu trúc mục tiêu.
- Tìm kiếm chuỗi SMARTS xuất hiện nhiều nhất.

Để biết thêm chi tiết các bạn có thể xem tại [TeachOpenCADD](https://projects.volkamerlab.org/teachopencadd/talktorials/T006_compound_maximum_common_substructures.html)
        
``` python
pip install rdkit
def find_core_smiles(smiles_list):
    mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
    mcs = rdFMCS.FindMCS(mols)
    core_smiles = Chem.MolToSmiles(Chem.MolFromSmarts(mcs.smartsString))
    return core_smiles
```

:::

<div class="group-title">"Khung của từng nhóm chất dựa MCS"</div>\n<div class="grid-container">" <div class="molecule-box"> <canvas id="canvas_a_Row0#0" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3OC)C)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#1" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3O)CCCO)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#2" width="150" height="150"></canvas> <div class="mol-name">Oc1ccc(cc1)C2Cc3cc(O)cc4c3C(c5c2c(cc(c5)O)O)C(O4)c6ccc(cc6)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#5" width="150" height="150"></canvas> <div class="mol-name">C=CCc1cc(OC)c(cc1)OC(CC)c2ccccc2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#7" width="150" height="150"></canvas> <div class="mol-name">**=Cc1cc(OC)c2c(c1)C(C)C(O2)c3ccc(c(c3)OC)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#9" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3)CCCO)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#10" width="150" height="150"></canvas> <div class="mol-name">c1cccc2c1C(c3cc(O)cc(c3)O)C(O2)c4ccc(cc4)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#11" width="150" height="150"></canvas> <div class="mol-name">**C1C2CC3N(C1*)C4C2C(C5(C3Nc6c5cccc6)C4)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#13" width="150" height="150"></canvas> <div class="mol-name">*c1cc(*)c2c(c1)Cc3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#14" width="150" height="150"></canvas> <div class="mol-name">*c1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#15" width="150" height="150"></canvas> <div class="mol-name">*c1ccc2c(c1)C(=O)c3c(C2=O)cccc3</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#16" width="150" height="150"></canvas> <div class="mol-name">Cc1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#17" width="150" height="150"></canvas> <div class="mol-name">*COC1OC(C2c3cccc(c3C(c4c2cc(cc4O)*)=O)O)C(C(C1O)O)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#18" width="150" height="150"></canvas> <div class="mol-name">*c1cc(*)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#20" width="150" height="150"></canvas> <div class="mol-name">O=C1c2ccccc2C(c3c1ccc(c3*)*)=O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#21" width="150" height="150"></canvas> <div class="mol-name">c1ccc2c3c1-c4ccccc4CC3NCC2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#22" width="150" height="150"></canvas> <div class="mol-name">Oc1ccc(cc1O)CC2c3c(cc(c(c3)O)OC)CCN2C</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#24" width="150" height="150"></canvas> <div class="mol-name">COc1ccc(cc1*)CC2NCCc3c2cccc3</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#26" width="150" height="150"></canvas> <div class="mol-name">COc1c(*)cc(cc1)CCNCCc2ccccc2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#27" width="150" height="150"></canvas> <div class="mol-name">COc1cc2c(cc1O)C(Cc3cccc(c3)O)N(CC2)C</div></div></div>


## 3. Tổng quan dược dân tộc học

Họ **Ericaceae** đã được một số công động tại các quốc gia như *Sicily, Turkey, Elsewhere, ain, Danish, French, German, US, US(Amerindian), US(Flathead), North America, China, Canada(Kwakiutl), Canada(Nootka), US(Makah), Japan, Dutch, Italian, India, Nepal, Europe* sử dụng trên lâm sàng bao gồm cả chữa bệnh cũng như cảnh báo về độc tính *chất gây say, chất khử trùng, chất làm se, thuốc lợi tiểu, tiêu hóa, giờ mở cửa, có mùi hôi, thuốc nhỏ mắt, thuốc chống thấp khớp, thuốc tống hơi, chất độc, thuốc diệt ký sinh trùng, thuốc trừ sâu, bàng quang, thuốc đắp, diệt khuẩn, thuốc giảm đau, dễ bị tổn thương, cầm máu, phân hủy đá, chất kích thích, thuốc diệt cá, thuốc an thần, ma túy, thuốc bổ, thuốc giải độc, dạ dày*. Bảng tổng kết chi tiết được trình bày ở dưới đây.

Các loài sử dụng phổ biến đề điều trị bệnh bao gồm *Chimaphila umbellata* (6 chứng và bệnh), *Pyrola rotundifolia* (6 chứng và bệnh), *Calluna vulgaris* (3 chứng và bệnh), *Gaultheria procumbens* (3 chứng và bệnh), *Monotropa uniflora* (3 chứng và bệnh).

Tiếp cận dựa trên chứng và bệnh để điều trị cho thấy các bệnh phổ biến mà các loài cho họ **Ericaceae** có thể điều trị là thuốc lợi tiểu (7 loài), chất độc (6 loài), chất khử trùng (5 loài), chất làm se (4 loài), ma túy (3 loài).

::: {.table caption="Bảng chi tiết các loài được làm thuốc từ họ Ericaceae"}
| <RowID>   | genus_GIBF   | Country- Species - Disease                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|-----------|--------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Row0      | Arbutus      | Sicily - (*Arbutus unedo* - chất gây say), Turkey - (*Arbutus unedo* - chất khử trùng)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| Row1      | Calluna      | Elsewhere - (*Calluna vulgaris* - chất làm se), Turkey - (*Calluna vulgaris* - chất khử trùng), ain - (*Calluna vulgaris* - thuốc lợi tiểu)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Row2      | Chimaphila   | Danish - (*Chimaphila umbellata* - thuốc lợi tiểu), French - (*Chimaphila umbellata* - tiêu hóa), German - (*Chimaphila umbellata* - giờ mở cửa), US - (*Chimaphila umbellata* - chất khử trùng), US(Amerindian) - (*Chimaphila umbellata* - có mùi hôi), US(Flathead) - (*Chimaphila umbellata* - thuốc nhỏ mắt)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Row3      | Epigaea      | Elsewhere - (*Epigaea repens* - chất làm se), French - (*Epigaea repens* - chất làm se), US - (*Epigaea repens* - thuốc lợi tiểu)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Row4      | Gaultheria   | Elsewhere - (*Gaultheria procumbens* - thuốc chống thấp khớp), Turkey - (*Gaultheria procumbens* - chất khử trùng), US - (*Gaultheria procumbens* - thuốc tống hơi)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| Row5      | Kalmia       | North America - (*Kalmia latifolia* - chất làm se), Turkey - (*Kalmia latifolia* - chất làm se), US - (*Kalmia latifolia* - chất độc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Row6      | Leucothoe    | China - (*Leucothoe grayana* - thuốc diệt ký sinh trùng)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Row7      | Lyonia       | Elsewhere - (*Lyonia ovalifolia* - thuốc trừ sâu)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Row8      | Moneses      | Canada(Kwakiutl) - (*Moneses uniflora* - bàng quang), Canada(Nootka) - (*Moneses uniflora* - thuốc đắp), US(Makah) - (*Moneses uniflora* - bàng quang)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| Row9      | Monotropa    | Elsewhere - (*Monotropa uniflora* - diệt khuẩn), US - (*Monotropa uniflora* - thuốc giảm đau), US(Amerindian) - (*Monotropa uniflora* - thuốc nhỏ mắt)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| Row10     | Pieris       | Elsewhere - (*Pieris formosa* - chất độc), Japan - (*Pieris japonica* - chất độc), US - (*Pieris japonica* - chất độc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| Row11     | Pyrola       | Elsewhere - (*Pyrola japonica* - thuốc lợi tiểu), China - (*Pyrola rotundifolia* - có mùi hôi), Dutch - (*Pyrola rotundifolia* - dễ bị tổn thương), Elsewhere - (*Pyrola rotundifolia* - chất làm se), French - (*Pyrola rotundifolia* - chất làm se), German - (*Pyrola rotundifolia* - cầm máu), Italian - (*Pyrola rotundifolia* - thuốc lợi tiểu), US - (*Pyrola rotundifolia* - phân hủy đá), ain - (*Pyrola rotundifolia* - thuốc lợi tiểu)                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Row12     | Rhododendron | India - (*Rhododendron anthopogon* - chất kích thích), Elsewhere - (*Rhododendron arboreum* - chất độc), Nepal - (*Rhododendron arboreum* - chất độc), India - (*Rhododendron barbatum* - thuốc diệt cá), Elsewhere - (*Rhododendron campanulatum* - chất độc), India - (*Rhododendron falconeri* - thuốc diệt cá), Europe - (*Rhododendron ferrugineum* - thuốc lợi tiểu), Turkey - (*Rhododendron ferrugineum* - thuốc lợi tiểu), ain - (*Rhododendron ferrugineum* - có mùi hôi), Elsewhere - (*Rhododendron groenlandicum* - ma túy), China - (*Rhododendron indicum* - thuốc an thần), Elsewhere - (*Rhododendron japonicum* - chất độc), Elsewhere - (*Rhododendron japonoheptamerum* - thuốc lợi tiểu), Elsewhere - (*Rhododendron lepidotum* - chất kích thích), China - (*Rhododendron molle* - thuốc trừ sâu), Elsewhere - (*Rhododendron ponticum* - ma túy), Turkey - (*Rhododendron ponticum* - chất gây say) |
| Row13     | Vaccinium    | US - (*Vaccinium arboreum* - thuốc bổ), Turkey - (*Vaccinium myrtillus* - thuốc giải độc), ain - (*Vaccinium myrtillus* - chất khử trùng), Europe - (*Vaccinium uliginosum* - dạ dày), Turkey - (*Vaccinium uliginosum* - ma túy)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
:::

## Chi tiết một số loài 

:::{#Ericaceae}
:::

<script src="https://cdn.jsdelivr.net/npm/smiles-drawer@2.0.1/dist/smiles-drawer.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const molecules = [
        {id: "canvas_a_Row0#0", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3OC)C)ccc1O" },
{id: "canvas_a_Row0#1", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3O)CCCO)ccc1O" },
{id: "canvas_a_Row0#2", smiles: "Oc1ccc(cc1)C2Cc3cc(O)cc4c3C(c5c2c(cc(c5)O)O)C(O4)c6ccc(cc6)O" },
{id: "canvas_a_Row0#5", smiles: "C=CCc1cc(OC)c(cc1)OC(CC)c2ccccc2" },
{id: "canvas_a_Row0#7", smiles: "**=Cc1cc(OC)c2c(c1)C(C)C(O2)c3ccc(c(c3)OC)O" },
{id: "canvas_a_Row0#9", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3)CCCO)ccc1O" },
{id: "canvas_a_Row0#10", smiles: "c1cccc2c1C(c3cc(O)cc(c3)O)C(O2)c4ccc(cc4)O" },
{id: "canvas_a_Row0#11", smiles: "**C1C2CC3N(C1*)C4C2C(C5(C3Nc6c5cccc6)C4)O" },
{id: "canvas_a_Row0#13", smiles: "*c1cc(*)c2c(c1)Cc3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#14", smiles: "*c1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#15", smiles: "*c1ccc2c(c1)C(=O)c3c(C2=O)cccc3" },
{id: "canvas_a_Row0#16", smiles: "Cc1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#17", smiles: "*COC1OC(C2c3cccc(c3C(c4c2cc(cc4O)*)=O)O)C(C(C1O)O)O" },
{id: "canvas_a_Row0#18", smiles: "*c1cc(*)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#20", smiles: "O=C1c2ccccc2C(c3c1ccc(c3*)*)=O" },
{id: "canvas_a_Row0#21", smiles: "c1ccc2c3c1-c4ccccc4CC3NCC2" },
{id: "canvas_a_Row0#22", smiles: "Oc1ccc(cc1O)CC2c3c(cc(c(c3)O)OC)CCN2C" },
{id: "canvas_a_Row0#24", smiles: "COc1ccc(cc1*)CC2NCCc3c2cccc3" },
{id: "canvas_a_Row0#26", smiles: "COc1c(*)cc(cc1)CCNCCc2ccccc2" },
{id: "canvas_a_Row0#27", smiles: "COc1cc2c(cc1O)C(Cc3cccc(c3)O)N(CC2)C" },
{id: "canvas_Row0", smiles: "CCC(CCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C)C(C)C" },
{id: "canvas_Row1", smiles: "CC[C@H](CC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4CC(O)CC[C@]4(C)[C@H]3CC[C@@]21C)C(C)C" },
{id: "canvas_Row2", smiles: "C[C@@H]1[C@H]2C3=CC[C@@H]4[C@@]5(C)CC[C@H](O)C(C)(C)[C@@H]5CC[C@@]4(C)[C@]3(C)CC[C@@]2(C(=O)O)CC[C@H]1C" },
{id: "canvas_Row3", smiles: "O=c1c(O[C@@H]2O[C@H](CO)[C@H](O)[C@H](O)[C@H]2O)c(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12" },
{id: "canvas_Row4", smiles: "CC1CCC2(C(=O)O)CCC3(C)C(=CCC4C5(C)CCC(O)C(C)(C)C5CCC43C)C2C1C" }
    ];
    const drawer = new SmilesDrawer.Drawer({ width: 150, height: 150 });
    molecules.forEach(mol => {
      SmilesDrawer.parse(mol.smiles, function (tree) {
        drawer.draw(tree, mol.id, "light", false);
      });
    });
  });
</script>

