---
title: Họ Smilacaceae
subtitle: Họ **Smilacaceae** gồm Smilax chi và 5 loài  được sử dụng ở 10vùng lãnh thổ điều trị 7chứng và bệnh.
description: Họ **Smilacaceae** gồm1 chi và 5loài đã ghi nhận sử dụng làm thuốc tại 10 vùng và lãnh thổ. Thống kê cho thầy các loài thuộc họ này có thể điều trị các chứng và bệnh phổ biến nhất gồm thuốc giải độc (3 loài), chất kích thích (2 loài), thuốc bổ (2 loài), có mùi hôi (1 loài), làm dịu (1 loài) . 05 loài thực vật gồm **Smilax china* (6 chứng và bệnh), *Smilax medica* (2 chứng và bệnh), *Smilax aristolochiifolia* (1 chứng và bệnh), *Smilax glabra* (1 chứng và bệnh), *Smilax ornata* (1 chứng và bệnh)* được xem là sử dụng điều trị nhiều chứng và bệnh nhất. Trong đó, các loài phân lập và xác định được nhiều thành phần nhất gồm *Smilax china* ( 88 hoạt chất), *Smilax glabra* ( 50 hoạt chất), *Smilax aristolochiifolia* ( 16 hoạt chất), *Smilax medica* ( 16 hoạt chất), *Smilax ornata* ( 4 hoạt chất). Loài dược liệu quan trọng thuộc họ này là *Smilax china*
author: "TS. Hoàng Lê Sơn"
image: http://n2t.net/ark:/65665/m3f51d32ae-c2fc-48b3-8a83-8a663bf135ea
toc: true
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
    include-in-header:
      - text: |
            <style>
                .group-title { font-size: 20px; font-weight: bold; margin-top: 30px; }
                .grid-container { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 20px; }
                .molecule-box { text-align: center; }
                canvas { border: 1px solid #ccc; }
                .mol-name { margin-top: 5px; font-weight: bold; font-size: 14px; }
            </style>
lightbox: auto
fig-cap-location: bottom
categories: ['Dược dân tộc']
listing:
  - id: Smilacaceae
    contents: Smilacaceae/*.qmd
    sort: "subtitle"
    type: table
    fields: [image, title, subtitle, description]
---

## 1.Tổng quan về thực vật

Họ Smilacaceae có tổng cộng 1  chi và 5 loài. 

::: {.table caption="Bảng các loài được sử dụng làm thuốc từ họ Smilacaceae"}

| <RowID>   | genus_GIBF   | species_GIBF                                                                        |   Count |
|-----------|--------------|-------------------------------------------------------------------------------------|---------|
| Row0      | Smilax       | Smilax aristolochiifolia, Smilax china, Smilax glabra, Smilax medica, Smilax ornata |       5 |

:::

Phân bố họ trên thế giới: United States of America, Mexico, El Salvador, Guatemala, Belize, Costa Rica, Peru, China, Chinese Taipei, Hong Kong, Japan, Korea, Republic of, Thailand, nan, Cambodia, Macao, Lao People’s Democratic Republic, Viet Nam, Belgium, Brazil, Venezuela (Bolivarian Republic of), Honduras, Russian Federation, unknown or invalid, Nicaragua, United Kingdom of Great Britain and Northern Ireland, Solomon Islands, Jamaica



<div id="map-leo" style="width: 100%; height: 600px;"></div>

<script src="https://cdn.plot.ly/plotly-3.1.0.min.js"></script>
<script>
const data = {
  title: "Bản đồ phân bố: Smilacaceae",
  iso3_codes: ['MEX', 'BRA', 'KHM', 'PER', 'JAM', 'CHN', 'RUS', 'SLB', 'THA', 'VNM', 'HND', 'GBR', 'HKG', 'CRI', 'NIC', 'SLV', 'BEL', 'JPN', 'USA', 'GTM', 'BLZ', 'MAC'],
  color: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
};
const trace = {
  type: "choropleth",
  locationmode: "ISO-3",
  locations: data.iso3_codes,
  z: data.color,
  colorscale: [[0, "#EAEAEA"], [1, "#FFB6C1"]],
  zmin: 0,
  zmax: 1,
  showscale: false
};
const layout = {
  title: {
    text: data.title,
    font: { size: 20 }
  },
  geo: {
    projection: { type: "natural earth" },
    showland: true,
    landcolor: "#EAEAEA",
    showcountries: true
  },
  margin: { l: 0, r: 0, t: 40, b: 0 }
};
Plotly.newPlot("map-leo", [trace], layout);
</script>


## 2. Tổng quan về thành phần hóa học

Từ **họ Smilacaceae** có tổng cộng 1  chi và 5 loài.đã phân lập và xác định được 174 hoạt chất từ một số nhóm chính Statistic_Group_Compound. Phân tích sâu hơn về thành phần hóa học giữa các nhóm chúng tôi đề xuất hai hướng tiếp cận sau.

### 2.1 Hợp chất tìm thấy nhiều nhất trong họ Smilacaceae

Sau khi tải dữ liệu từ Lotus, các hợp chất sẽ được thống kê lại xem đâu là hoạt chất có tần số xuất hiện trong các loài nhiều nhất. 
<div class="group-title">"Hoạt chất phổ biến trong họ"</div>\n<div class="grid-container">" <div class="molecule-box"> <canvas id="canvas_Row0" width="150" height="150"></canvas> <div class="mol-name">LTS0102637</div></div> <div class="molecule-box"> <canvas id="canvas_Row1" width="150" height="150"></canvas> <div class="mol-name">LTS0003890</div></div> <div class="molecule-box"> <canvas id="canvas_Row2" width="150" height="150"></canvas> <div class="mol-name">LTS0020004</div></div> <div class="molecule-box"> <canvas id="canvas_Row3" width="150" height="150"></canvas> <div class="mol-name">LTS0029891</div></div> <div class="molecule-box"> <canvas id="canvas_Row4" width="150" height="150"></canvas> <div class="mol-name">LTS0042221</div></div></div>

### 2.2 Tìm kiếm sự tương đồng

::: {.callout-note title = "Find Maximum Common Substructure" }
        
Thuật toán FMCS (Find Maximum Common Substructure) là một phương pháp được sử dụng để tìm ra cấu trúc chung nhiều nhất (MCS) trong một tập hợp các cấu trúc hóa học. Các bước của thuật toán gồm:
        
- Chọn một cấu trúc hóa học là cấu trúc để tạo truy vấn, còn các cấu trúc khác là mục tiêu.
- Chia nhỏ cấu trúc để tạo truy vấn thành cấu trúc nhỏ hơn dạng chuỗi SMARTS.
- Kiểm tra chuỗi SMARTS trong các cấu trúc mục tiêu.
- Tìm kiếm chuỗi SMARTS xuất hiện nhiều nhất.

Để biết thêm chi tiết các bạn có thể xem tại [TeachOpenCADD](https://projects.volkamerlab.org/teachopencadd/talktorials/T006_compound_maximum_common_substructures.html)
        
``` python
pip install rdkit
def find_core_smiles(smiles_list):
    mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
    mcs = rdFMCS.FindMCS(mols)
    core_smiles = Chem.MolToSmiles(Chem.MolFromSmarts(mcs.smartsString))
    return core_smiles
```

:::

<div class="group-title">"Khung của từng nhóm chất dựa MCS"</div>\n<div class="grid-container">" <div class="molecule-box"> <canvas id="canvas_a_Row0#0" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3OC)C)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#1" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3O)CCCO)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#2" width="150" height="150"></canvas> <div class="mol-name">Oc1ccc(cc1)C2Cc3cc(O)cc4c3C(c5c2c(cc(c5)O)O)C(O4)c6ccc(cc6)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#5" width="150" height="150"></canvas> <div class="mol-name">C=CCc1cc(OC)c(cc1)OC(CC)c2ccccc2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#7" width="150" height="150"></canvas> <div class="mol-name">**=Cc1cc(OC)c2c(c1)C(C)C(O2)c3ccc(c(c3)OC)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#9" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3)CCCO)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#10" width="150" height="150"></canvas> <div class="mol-name">c1cccc2c1C(c3cc(O)cc(c3)O)C(O2)c4ccc(cc4)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#11" width="150" height="150"></canvas> <div class="mol-name">**C1C2CC3N(C1*)C4C2C(C5(C3Nc6c5cccc6)C4)O</div></div></div>


## 3. Tổng quan dược dân tộc học

Họ **Smilacaceae** đã được một số công động tại các quốc gia như *Egypt, China, Dutch, Elsewhere, English, India, Malaya, anish, Mexico, Central America* sử dụng trên lâm sàng bao gồm cả chữa bệnh cũng như cảnh báo về độc tính *thuốc bổ, thuốc tống hơi, làm dịu, có mùi hôi, thuốc giải độc, thuốc kích thích tình dục, chất kích thích*. Bảng tổng kết chi tiết được trình bày ở dưới đây.

Các loài sử dụng phổ biến đề điều trị bệnh bao gồm *Smilax china* (6 chứng và bệnh), *Smilax medica* (2 chứng và bệnh), *Smilax aristolochiifolia* (1 chứng và bệnh), *Smilax glabra* (1 chứng và bệnh), *Smilax ornata* (1 chứng và bệnh).

Tiếp cận dựa trên chứng và bệnh để điều trị cho thấy các bệnh phổ biến mà các loài cho họ **Smilacaceae** có thể điều trị là thuốc giải độc (3 loài), chất kích thích (2 loài), thuốc bổ (2 loài), có mùi hôi (1 loài), làm dịu (1 loài).

::: {.table caption="Bảng chi tiết các loài được làm thuốc từ họ Smilacaceae"}
| <RowID>   | genus_GIBF   | Country- Species - Disease                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|-----------|--------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Row0      | Smilax       | Egypt - (*Smilax aristolochiifolia* - thuốc bổ), China - (*Smilax china* - thuốc tống hơi), Dutch - (*Smilax china* - làm dịu), Egypt - (*Smilax china* - có mùi hôi), Elsewhere - (*Smilax china* - thuốc giải độc), English - (*Smilax china* - thuốc kích thích tình dục), India - (*Smilax china* - thuốc kích thích tình dục), Malaya - (*Smilax china* - thuốc kích thích tình dục), anish - (*Smilax china* - chất kích thích), China - (*Smilax glabra* - thuốc giải độc), Elsewhere - (*Smilax medica* - thuốc giải độc), Mexico - (*Smilax medica* - chất kích thích), Central America - (*Smilax ornata* - thuốc bổ) |
:::

## Chi tiết một số loài 

:::{#Smilacaceae}
:::

<script src="https://cdn.jsdelivr.net/npm/smiles-drawer@2.0.1/dist/smiles-drawer.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const molecules = [
        {id: "canvas_a_Row0#0", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3OC)C)ccc1O" },
{id: "canvas_a_Row0#1", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3O)CCCO)ccc1O" },
{id: "canvas_a_Row0#2", smiles: "Oc1ccc(cc1)C2Cc3cc(O)cc4c3C(c5c2c(cc(c5)O)O)C(O4)c6ccc(cc6)O" },
{id: "canvas_a_Row0#5", smiles: "C=CCc1cc(OC)c(cc1)OC(CC)c2ccccc2" },
{id: "canvas_a_Row0#7", smiles: "**=Cc1cc(OC)c2c(c1)C(C)C(O2)c3ccc(c(c3)OC)O" },
{id: "canvas_a_Row0#9", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3)CCCO)ccc1O" },
{id: "canvas_a_Row0#10", smiles: "c1cccc2c1C(c3cc(O)cc(c3)O)C(O2)c4ccc(cc4)O" },
{id: "canvas_a_Row0#11", smiles: "**C1C2CC3N(C1*)C4C2C(C5(C3Nc6c5cccc6)C4)O" },
{id: "canvas_Row0", smiles: "CC1CCC2(OC1)OC1CC3C4CCC5CC(OC6OC(COC7OC(CO)C(O)C(O)C7O)C(OC7OC(C)C(O)C(O)C7O)C(O)C6OC6OC(CO)C(O)C(O)C6O)CCC5(C)C4CCC3(C)C1C2C" },
{id: "canvas_Row1", smiles: "COC1(CCC(C)COC2OC(CO)C(O)C(O)C2O)OC2CC3C4CCC5CC(OC6OC(COC7OC(CO)C(O)C(O)C7O)C(OC7OC(CO)C(O)C(O)C7O)C(O)C6OC6OC(CO)C(O)C(O)C6O)CCC5(C)C4CCC3(C)C2C1C" },
{id: "canvas_Row2", smiles: "C[C@H]1[C@H]2[C@H](C[C@H]3[C@@H]4CC[C@@H]5C[C@@H](O)CC[C@]5(C)[C@H]4CC[C@@]32C)O[C@]12CC[C@@H](C)CO2" },
{id: "canvas_Row3", smiles: "CC1CCC2(OC1)OC1CC3C4CCC5CC(OC6OC(COC7OC(CO)C(O)C(O)C7O)C(OC7OC(CO)C(O)C(O)C7O)C(O)C6O)CCC5(C)C4CCC3(C)C1C2C" },
{id: "canvas_Row4", smiles: "CC1CCC2(OC1)OC1CC3C4CCC5CC(OC6OC(COC7OC(CO)C(O)C(O)C7O)C(OC7OC(CO)C(O)C(O)C7O)C(O)C6OC6OC(CO)C(O)C(O)C6O)CCC5(C)C4CCC3(C)C1C2C" }
    ];
    const drawer = new SmilesDrawer.Drawer({ width: 150, height: 150 });
    molecules.forEach(mol => {
      SmilesDrawer.parse(mol.smiles, function (tree) {
        drawer.draw(tree, mol.id, "light", false);
      });
    });
  });
</script>

