---
title: Họ Lauraceae
subtitle: Họ **Lauraceae** gồm Alseodaphne, Beilschmiedia, Cassytha, Cinnamomum, Cryptocarya, Laurus, Lindera, Litsea, Persea, Sassafras chi và 22 loài  được sử dụng ở 23vùng lãnh thổ điều trị 22chứng và bệnh.
description: Họ **Lauraceae** gồm10 chi và 22loài đã ghi nhận sử dụng làm thuốc tại 23 vùng và lãnh thổ. Thống kê cho thầy các loài thuộc họ này có thể điều trị các chứng và bệnh phổ biến nhất gồm thuốc tống hơi (7 loài), chất làm se (6 loài), chất độc (4 loài), chất khử trùng (3 loài), dạ dày (3 loài) . 05 loài thực vật gồm **Persea americana* (8 chứng và bệnh), *Cinnamomum burmanni* (4 chứng và bệnh), *Cinnamomum camphora* (4 chứng và bệnh), *Cinnamomum verum* (3 chứng và bệnh), *Sassafras albidum* (3 chứng và bệnh)* được xem là sử dụng điều trị nhiều chứng và bệnh nhất. Trong đó, các loài phân lập và xác định được nhiều thành phần nhất gồm *Laurus nobilis* ( 198 hoạt chất), *Persea americana* ( 172 hoạt chất), *Cinnamomum burmanni* ( 130 hoạt chất), *Cinnamomum sieboldii* ( 122 hoạt chất), *Cinnamomum verum* ( 121 hoạt chất). Loài dược liệu quan trọng thuộc họ này là *Laurus nobilis*
author: "TS. Hoàng Lê Sơn"
image: http://data.huh.harvard.edu/da5b91f6-26c6-49c4-b0f7-007201de081f/image
toc: true
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
    include-in-header:
      - text: |
            <style>
                .group-title { font-size: 20px; font-weight: bold; margin-top: 30px; }
                .grid-container { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 20px; }
                .molecule-box { text-align: center; }
                canvas { border: 1px solid #ccc; }
                .mol-name { margin-top: 5px; font-weight: bold; font-size: 14px; }
            </style>
lightbox: auto
fig-cap-location: bottom
categories: ['Dược dân tộc']
listing:
  - id: Lauraceae
    contents: Lauraceae/*.qmd
    sort: "subtitle"
    type: table
    fields: [image, title, subtitle, description]
---

## 1.Tổng quan về thực vật

Họ Lauraceae có tổng cộng 10  chi và 22 loài. 

::: {.table caption="Bảng các loài được sử dụng làm thuốc từ họ Lauraceae"}

| <RowID>   | genus_GIBF    | species_GIBF                                                                                                                                                     |   Count |
|-----------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
| Row3      | Cinnamomum    | Cinnamomum aromaticum, Cinnamomum camphora, Cinnamomum iners, Cinnamomum oliveri, Cinnamomum sieboldii, Cinnamomum tamala, Cinnamomum verum, Cinnamomum burmanni |       8 |
| Row6      | Lindera       | Lindera benzoin, Lindera glauca, Lindera pipericarpa, Lindera sericea                                                                                            |       4 |
| Row7      | Litsea        | Litsea cubeba, Litsea glutinosa, Litsea monopetala                                                                                                               |       3 |
| Row0      | Alseodaphne   | Alseodaphne perakensis                                                                                                                                           |       1 |
| Row1      | Beilschmiedia | Beilschmiedia madang                                                                                                                                             |       1 |
| Row2      | Cassytha      | Cassytha filiformis                                                                                                                                              |       1 |
| Row4      | Cryptocarya   | Cryptocarya griffithiana                                                                                                                                         |       1 |
| Row5      | Laurus        | Laurus nobilis                                                                                                                                                   |       1 |
| Row8      | Persea        | Persea americana                                                                                                                                                 |       1 |
| Row9      | Sassafras     | Sassafras albidum                                                                                                                                                |       1 |

:::

Phân bố họ trên thế giới: nan, Malaysia, Indonesia, unknown or invalid, Singapore, Cook Islands, Turks and Caicos Islands, Micronesia (Federated States of), Marshall Islands, New Caledonia, Bahamas, Cuba, Jamaica, French Guiana, Mexico, Chinese Taipei, Hong Kong, Liberia, South Africa, Belize, Japan, Australia, Tuvalu, Trinidad and Tobago, Nigeria, Niue, Mozambique, India, Palau, Brazil, Northern Mariana Islands, Thailand, United States of America, Ethiopia, Dominican Republic, Fiji, Samoa, Puerto Rico, Sierra Leone, Germany, Sri Lanka, Colombia, Papua New Guinea, Cambodia, Honduras, Guatemala, Viet Nam, Philippines, China, Afghanistan, Iran (Islamic Republic of), Lao People’s Democratic Republic, New Zealand, Uruguay, Myanmar, Brunei Darussalam, Belgium, Russian Federation, Korea, Republic of, Portugal, Pakistan, Bangladesh, Bhutan, Nepal, Mayotte, Seychelles, Guadeloupe, Martinique, Panama, Sao Tome and Principe, Mauritius, Dominica, Costa Rica, Argentina, Nicaragua, El Salvador, Tanzania, United Republic of, Ghana, Cameroon, Madagascar, Paraguay, Togo, Uganda, Norway, Ecuador, Guinea, Montenegro, Türkiye, Georgia, Switzerland, Netherlands, Cyprus, Croatia, Malta, Italy, Ireland, Palestine, State of, Greece, Chile, Algeria, Israel, Monaco, France, Spain, United Kingdom of Great Britain and Northern Ireland, Canada, Réunion, Lebanon, Saint Vincent and the Grenadines, Haiti, Vanuatu, French Polynesia, Venezuela (Bolivarian Republic of), Rwanda, United Arab Emirates, Peru, Anguilla, Macao



<div id="map-leo" style="width: 100%; height: 600px;"></div>

<script src="https://cdn.plot.ly/plotly-3.1.0.min.js"></script>
<script>
const data = {
  title: "Bản đồ phân bố: Lauraceae",
  iso3_codes: ['MMR', 'BRA', 'JPN', 'MDG', 'BEL', 'MNP', 'CMR', 'LKA', 'GRC', 'CUB', 'GUF', 'MUS', 'RUS', 'MOZ', 'HND', 'ZAF', 'TUR', 'TTO', 'BGD', 'GEO', 'THA', 'COL', 'SGP', 'CHN', 'GIN', 'MYT', 'DOM', 'BRN', 'PHL', 'AIA', 'CYP', 'IDN', 'BTN', 'COK', 'DMA', 'PAK', 'GBR', 'GTM', 'NCL', 'PRT', 'MYS', 'STP', 'JAM', 'NIC', 'VUT', 'VNM', 'MAC', 'LBN', 'BLZ', 'NLD', 'USA', 'ESP', 'URY', 'PER', 'GLP', 'CRI', 'MEX', 'PNG', 'TCA', 'ARG', 'TZA', 'CHL', 'FRA', 'MHL', 'WSM', 'PLW', 'IRL', 'ARE', 'NZL', 'PAN', 'GHA', 'NGA', 'TUV', 'PRI', 'SLV', 'SYC', 'FJI', 'HRV', 'LBR', 'HKG', 'MTQ', 'AFG', 'DEU', 'SLE', 'CHE', 'ECU', 'DZA', 'MLT', 'UGA', 'VCT', 'MCO', 'AUS', 'PYF', 'NPL', 'KHM', 'CAN', 'MNE', 'REU', 'HTI', 'ITA', 'BHS', 'ETH', 'NIU', 'NOR', 'PRY', 'ISR', 'RWA', 'IND', 'TGO'],
  color: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
};
const trace = {
  type: "choropleth",
  locationmode: "ISO-3",
  locations: data.iso3_codes,
  z: data.color,
  colorscale: [[0, "#EAEAEA"], [1, "#FFB6C1"]],
  zmin: 0,
  zmax: 1,
  showscale: false
};
const layout = {
  title: {
    text: data.title,
    font: { size: 20 }
  },
  geo: {
    projection: { type: "natural earth" },
    showland: true,
    landcolor: "#EAEAEA",
    showcountries: true
  },
  margin: { l: 0, r: 0, t: 40, b: 0 }
};
Plotly.newPlot("map-leo", [trace], layout);
</script>


## 2. Tổng quan về thành phần hóa học

Từ **họ Lauraceae** có tổng cộng 10  chi và 22 loài.đã phân lập và xác định được 1440 hoạt chất từ một số nhóm chính Statistic_Group_Compound. Phân tích sâu hơn về thành phần hóa học giữa các nhóm chúng tôi đề xuất hai hướng tiếp cận sau.

### 2.1 Hợp chất tìm thấy nhiều nhất trong họ Lauraceae

Sau khi tải dữ liệu từ Lotus, các hợp chất sẽ được thống kê lại xem đâu là hoạt chất có tần số xuất hiện trong các loài nhiều nhất. 
<div class="group-title">"Hoạt chất phổ biến trong họ"</div>\n<div class="grid-container">" <div class="molecule-box"> <canvas id="canvas_Row0" width="150" height="150"></canvas> <div class="mol-name">LTS0155981</div></div> <div class="molecule-box"> <canvas id="canvas_Row1" width="150" height="150"></canvas> <div class="mol-name">LTS0117550</div></div> <div class="molecule-box"> <canvas id="canvas_Row2" width="150" height="150"></canvas> <div class="mol-name">LTS0128839</div></div> <div class="molecule-box"> <canvas id="canvas_Row3" width="150" height="150"></canvas> <div class="mol-name">LTS0132416</div></div> <div class="molecule-box"> <canvas id="canvas_Row4" width="150" height="150"></canvas> <div class="mol-name">LTS0136148</div></div></div>

### 2.2 Tìm kiếm sự tương đồng

::: {.callout-note title = "Find Maximum Common Substructure" }
        
Thuật toán FMCS (Find Maximum Common Substructure) là một phương pháp được sử dụng để tìm ra cấu trúc chung nhiều nhất (MCS) trong một tập hợp các cấu trúc hóa học. Các bước của thuật toán gồm:
        
- Chọn một cấu trúc hóa học là cấu trúc để tạo truy vấn, còn các cấu trúc khác là mục tiêu.
- Chia nhỏ cấu trúc để tạo truy vấn thành cấu trúc nhỏ hơn dạng chuỗi SMARTS.
- Kiểm tra chuỗi SMARTS trong các cấu trúc mục tiêu.
- Tìm kiếm chuỗi SMARTS xuất hiện nhiều nhất.

Để biết thêm chi tiết các bạn có thể xem tại [TeachOpenCADD](https://projects.volkamerlab.org/teachopencadd/talktorials/T006_compound_maximum_common_substructures.html)
        
``` python
pip install rdkit
def find_core_smiles(smiles_list):
    mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
    mcs = rdFMCS.FindMCS(mols)
    core_smiles = Chem.MolToSmiles(Chem.MolFromSmarts(mcs.smartsString))
    return core_smiles
```

:::

<div class="group-title">"Khung của từng nhóm chất dựa MCS"</div>\n<div class="grid-container">" <div class="molecule-box"> <canvas id="canvas_a_Row0#0" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3OC)C)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#1" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3O)CCCO)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#2" width="150" height="150"></canvas> <div class="mol-name">Oc1ccc(cc1)C2Cc3cc(O)cc4c3C(c5c2c(cc(c5)O)O)C(O4)c6ccc(cc6)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#5" width="150" height="150"></canvas> <div class="mol-name">C=CCc1cc(OC)c(cc1)OC(CC)c2ccccc2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#7" width="150" height="150"></canvas> <div class="mol-name">**=Cc1cc(OC)c2c(c1)C(C)C(O2)c3ccc(c(c3)OC)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#9" width="150" height="150"></canvas> <div class="mol-name">COc1cc(C2Oc3c(C2CO)cc(cc3)CCCO)ccc1O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#10" width="150" height="150"></canvas> <div class="mol-name">c1cccc2c1C(c3cc(O)cc(c3)O)C(O2)c4ccc(cc4)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#11" width="150" height="150"></canvas> <div class="mol-name">**C1C2CC3N(C1*)C4C2C(C5(C3Nc6c5cccc6)C4)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#13" width="150" height="150"></canvas> <div class="mol-name">*c1cc(*)c2c(c1)Cc3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#14" width="150" height="150"></canvas> <div class="mol-name">*c1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#15" width="150" height="150"></canvas> <div class="mol-name">*c1ccc2c(c1)C(=O)c3c(C2=O)cccc3</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#16" width="150" height="150"></canvas> <div class="mol-name">Cc1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#17" width="150" height="150"></canvas> <div class="mol-name">*COC1OC(C2c3cccc(c3C(c4c2cc(cc4O)*)=O)O)C(C(C1O)O)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#18" width="150" height="150"></canvas> <div class="mol-name">*c1cc(*)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#20" width="150" height="150"></canvas> <div class="mol-name">O=C1c2ccccc2C(c3c1ccc(c3*)*)=O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#21" width="150" height="150"></canvas> <div class="mol-name">c1ccc2c3c1-c4ccccc4CC3NCC2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#22" width="150" height="150"></canvas> <div class="mol-name">Oc1ccc(cc1O)CC2c3c(cc(c(c3)O)OC)CCN2C</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#24" width="150" height="150"></canvas> <div class="mol-name">COc1ccc(cc1*)CC2NCCc3c2cccc3</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#26" width="150" height="150"></canvas> <div class="mol-name">COc1c(*)cc(cc1)CCNCCc2ccccc2</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#27" width="150" height="150"></canvas> <div class="mol-name">COc1cc2c(cc1O)C(Cc3cccc(c3)O)N(CC2)C</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#28" width="150" height="150"></canvas> <div class="mol-name">COc1ccc(cc1O)CC2c3c(cc(c(c3)O)OC)CCN2C</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#29" width="150" height="150"></canvas> <div class="mol-name">c1cc2c(cc1)C(c3ccccc3)C(C(=C2)C)C</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#30" width="150" height="150"></canvas> <div class="mol-name">CCC1(CCCN2C1C(CC2)(C(=*C(=O)*C)*)c3ccccc3)C</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#31" width="150" height="150"></canvas> <div class="mol-name">C(CCC1(*)CCCC2=C3C1CC(C3CC2)C(=O)OC)*(C)*</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#32" width="150" height="150"></canvas> <div class="mol-name">O=C(O)c1cc(O)c(c(c1)O)O</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#33" width="150" height="150"></canvas> <div class="mol-name">*=C(*)c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#34" width="150" height="150"></canvas> <div class="mol-name">**C(=*)c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#35" width="150" height="150"></canvas> <div class="mol-name">**c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#36" width="150" height="150"></canvas> <div class="mol-name">*=Cc1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#37" width="150" height="150"></canvas> <div class="mol-name">*=*c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#38" width="150" height="150"></canvas> <div class="mol-name">*=*c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#39" width="150" height="150"></canvas> <div class="mol-name">**Cc1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#41" width="150" height="150"></canvas> <div class="mol-name">*=*c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#42" width="150" height="150"></canvas> <div class="mol-name">C(*)(*)C(O)c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#43" width="150" height="150"></canvas> <div class="mol-name">O=C(O)c1ccccc1</div></div> <div class="molecule-box"> <canvas id="canvas_a_Row0#44" width="150" height="150"></canvas> <div class="mol-name">*=C(O)c1ccc(c(c1)*)O</div></div></div>


## 3. Tổng quan dược dân tộc học

Họ **Lauraceae** đã được một số công động tại các quốc gia như *Malaya, Borneo, Elsewhere, Java, China, Nepal, Turkey, US, Japan*, ain, US(Appalachia), Philippines, Dominican Republic, Guatemala, Haiti, Latin America, Mexico, Panama, Paraguay, Venezuela, German, Malaysia, anish* sử dụng trên lâm sàng bao gồm cả chữa bệnh cũng như cảnh báo về độc tính *chất độc, chất làm se, thuốc tẩy giun, thuốc an thần, thuốc giải độc, thuốc tống hơi, thuốc xông khói, chất kích thích, đổ mồ hôi, chất khử trùng, dạ dày, có mùi hôi, thuốc bổ, mỹ phẩm, cầm máu, thuốc long đờm, emmenagogue, kháng sinh, thuốc kích thích tình dục, giờ mở cửa, chống khả năng sinh sản, thuốc giảm đau*. Bảng tổng kết chi tiết được trình bày ở dưới đây.

Các loài sử dụng phổ biến đề điều trị bệnh bao gồm *Persea americana* (8 chứng và bệnh), *Cinnamomum burmanni* (4 chứng và bệnh), *Cinnamomum camphora* (4 chứng và bệnh), *Cinnamomum verum* (3 chứng và bệnh), *Sassafras albidum* (3 chứng và bệnh).

Tiếp cận dựa trên chứng và bệnh để điều trị cho thấy các bệnh phổ biến mà các loài cho họ **Lauraceae** có thể điều trị là thuốc tống hơi (7 loài), chất làm se (6 loài), chất độc (4 loài), chất khử trùng (3 loài), dạ dày (3 loài).

::: {.table caption="Bảng chi tiết các loài được làm thuốc từ họ Lauraceae"}
| <RowID>   | genus_GIBF    | Country- Species - Disease                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|-----------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Row0      | Alseodaphne   | Malaya - (*Alseodaphne perakensis* - chất độc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Row1      | Beilschmiedia | Borneo - (*Beilschmiedia madang* - chất làm se)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Row2      | Cassytha      | Elsewhere - (*Cassytha filiformis* - chất độc), Java - (*Cassytha filiformis* - thuốc tẩy giun)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Row3      | Cinnamomum    | China - (*Cinnamomum aromaticum* - thuốc an thần), German - (*Cinnamomum burmanni* - chất khử trùng), Malaysia - (*Cinnamomum burmanni* - dạ dày), US - (*Cinnamomum burmanni* - chất làm se), anish - (*Cinnamomum burmanni* - thuốc tống hơi), China - (*Cinnamomum camphora* - thuốc tẩy giun), Elsewhere - (*Cinnamomum camphora* - thuốc giải độc), Nepal - (*Cinnamomum camphora* - thuốc tống hơi), Turkey - (*Cinnamomum camphora* - thuốc xông khói), Elsewhere - (*Cinnamomum iners* - thuốc tống hơi), US - (*Cinnamomum oliveri* - chất kích thích), Japan* - (*Cinnamomum sieboldii* - đổ mồ hôi), Elsewhere - (*Cinnamomum tamala* - thuốc tống hơi), Nepal - (*Cinnamomum tamala* - chất làm se), Elsewhere - (*Cinnamomum verum* - chất làm se), Japan* - (*Cinnamomum verum* - đổ mồ hôi), Turkey - (*Cinnamomum verum* - chất khử trùng) |
| Row4      | Cryptocarya   | Elsewhere - (*Cryptocarya griffithiana* - chất độc), Malaya - (*Cryptocarya griffithiana* - chất độc)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Row5      | Laurus        | Elsewhere - (*Laurus nobilis* - dạ dày), Turkey - (*Laurus nobilis* - thuốc tống hơi), ain - (*Laurus nobilis* - dạ dày)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Row6      | Lindera       | US - (*Lindera benzoin* - có mùi hôi), US(Appalachia) - (*Lindera benzoin* - thuốc bổ), China - (*Lindera glauca* - dạ dày), Java - (*Lindera pipericarpa* - mỹ phẩm), China - (*Lindera sericea* - cầm máu)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| Row7      | Litsea        | China - (*Litsea cubeba* - thuốc long đờm), Elsewhere - (*Litsea glutinosa* - chất làm se), Philippines - (*Litsea glutinosa* - emmenagogue), Elsewhere - (*Litsea monopetala* - chất làm se)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Row8      | Persea        | Dominican Republic - (*Persea americana* - thuốc tống hơi), Elsewhere - (*Persea americana* - kháng sinh), Guatemala - (*Persea americana* - thuốc kích thích tình dục), Haiti - (*Persea americana* - giờ mở cửa), Latin America - (*Persea americana* - chất độc), Mexico - (*Persea americana* - emmenagogue), Panama - (*Persea americana* - emmenagogue), Paraguay - (*Persea americana* - chống khả năng sinh sản), Turkey - (*Persea americana* - mỹ phẩm), Venezuela - (*Persea americana* - thuốc kích thích tình dục)                                                                                                                                                                                                                                                                                                                            |
| Row9      | Sassafras     | Elsewhere - (*Sassafras albidum* - thuốc giảm đau), Turkey - (*Sassafras albidum* - chất khử trùng), US - (*Sassafras albidum* - thuốc tống hơi)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
:::

## Chi tiết một số loài 

:::{#Lauraceae}
:::

<script src="https://cdn.jsdelivr.net/npm/smiles-drawer@2.0.1/dist/smiles-drawer.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const molecules = [
        {id: "canvas_a_Row0#0", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3OC)C)ccc1O" },
{id: "canvas_a_Row0#1", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3O)CCCO)ccc1O" },
{id: "canvas_a_Row0#2", smiles: "Oc1ccc(cc1)C2Cc3cc(O)cc4c3C(c5c2c(cc(c5)O)O)C(O4)c6ccc(cc6)O" },
{id: "canvas_a_Row0#5", smiles: "C=CCc1cc(OC)c(cc1)OC(CC)c2ccccc2" },
{id: "canvas_a_Row0#7", smiles: "**=Cc1cc(OC)c2c(c1)C(C)C(O2)c3ccc(c(c3)OC)O" },
{id: "canvas_a_Row0#9", smiles: "COc1cc(C2Oc3c(C2CO)cc(cc3)CCCO)ccc1O" },
{id: "canvas_a_Row0#10", smiles: "c1cccc2c1C(c3cc(O)cc(c3)O)C(O2)c4ccc(cc4)O" },
{id: "canvas_a_Row0#11", smiles: "**C1C2CC3N(C1*)C4C2C(C5(C3Nc6c5cccc6)C4)O" },
{id: "canvas_a_Row0#13", smiles: "*c1cc(*)c2c(c1)Cc3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#14", smiles: "*c1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#15", smiles: "*c1ccc2c(c1)C(=O)c3c(C2=O)cccc3" },
{id: "canvas_a_Row0#16", smiles: "Cc1cc(O)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#17", smiles: "*COC1OC(C2c3cccc(c3C(c4c2cc(cc4O)*)=O)O)C(C(C1O)O)O" },
{id: "canvas_a_Row0#18", smiles: "*c1cc(*)c2c(c1)C(=O)c3c(C2=O)c(ccc3)O" },
{id: "canvas_a_Row0#20", smiles: "O=C1c2ccccc2C(c3c1ccc(c3*)*)=O" },
{id: "canvas_a_Row0#21", smiles: "c1ccc2c3c1-c4ccccc4CC3NCC2" },
{id: "canvas_a_Row0#22", smiles: "Oc1ccc(cc1O)CC2c3c(cc(c(c3)O)OC)CCN2C" },
{id: "canvas_a_Row0#24", smiles: "COc1ccc(cc1*)CC2NCCc3c2cccc3" },
{id: "canvas_a_Row0#26", smiles: "COc1c(*)cc(cc1)CCNCCc2ccccc2" },
{id: "canvas_a_Row0#27", smiles: "COc1cc2c(cc1O)C(Cc3cccc(c3)O)N(CC2)C" },
{id: "canvas_a_Row0#28", smiles: "COc1ccc(cc1O)CC2c3c(cc(c(c3)O)OC)CCN2C" },
{id: "canvas_a_Row0#29", smiles: "c1cc2c(cc1)C(c3ccccc3)C(C(=C2)C)C" },
{id: "canvas_a_Row0#30", smiles: "CCC1(CCCN2C1C(CC2)(C(=*C(=O)*C)*)c3ccccc3)C" },
{id: "canvas_a_Row0#31", smiles: "C(CCC1(*)CCCC2=C3C1CC(C3CC2)C(=O)OC)*(C)*" },
{id: "canvas_a_Row0#32", smiles: "O=C(O)c1cc(O)c(c(c1)O)O" },
{id: "canvas_a_Row0#33", smiles: "*=C(*)c1ccccc1" },
{id: "canvas_a_Row0#34", smiles: "**C(=*)c1ccccc1" },
{id: "canvas_a_Row0#35", smiles: "**c1ccccc1" },
{id: "canvas_a_Row0#36", smiles: "*=Cc1ccccc1" },
{id: "canvas_a_Row0#37", smiles: "*=*c1ccccc1" },
{id: "canvas_a_Row0#38", smiles: "*=*c1ccccc1" },
{id: "canvas_a_Row0#39", smiles: "**Cc1ccccc1" },
{id: "canvas_a_Row0#41", smiles: "*=*c1ccccc1" },
{id: "canvas_a_Row0#42", smiles: "C(*)(*)C(O)c1ccccc1" },
{id: "canvas_a_Row0#43", smiles: "O=C(O)c1ccccc1" },
{id: "canvas_a_Row0#44", smiles: "*=C(O)c1ccc(c(c1)*)O" },
{id: "canvas_Row0", smiles: "C=C(C)C1CC=C(C)CC1" },
{id: "canvas_Row1", smiles: "C=C1CCC2CC1C2(C)C" },
{id: "canvas_Row2", smiles: "C=CC(C)(O)CCC=C(C)C" },
{id: "canvas_Row3", smiles: "CC1=CCC2CC1C2(C)C" },
{id: "canvas_Row4", smiles: "CC1=CCC(C(C)(C)O)CC1" }
    ];
    const drawer = new SmilesDrawer.Drawer({ width: 150, height: 150 });
    molecules.forEach(mol => {
      SmilesDrawer.parse(mol.smiles, function (tree) {
        drawer.draw(tree, mol.id, "light", false);
      });
    });
  });
</script>

