---
title: Cortex Strychni Wallichianae
subtitle: Hoàng Nàn - Vỏ Thân, Vỏ Cành
description: "Dược liệu Hoàng Nàn - Vỏ Thân, Vỏ Cành từ Vỏ Thân, Vỏ Cành của loài *Strychnos wallichiana* thuộc Họ Ranunculaceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: http://n2t.net/ark:/65665/m3c821e52b-b2ba-42af-89a1-0d3b9d748265
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Cortex Strychni Wallichianae/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Cortex Strychni Wallichianae/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Cortex Strychni Wallichianae/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Cortex Strychni Wallichianae/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Ranunculaceae
tags: [Strychnos wallichiana, Ranunculaceae]
---

::: {.callout-note title = "Tóm tắt"}

Hoàng nàn (Cortex Strychni wallichianae) thuộc họ Mã tiền (Loganiaceae). Theo KEW, cây này được phân bố tại Nam Trung Quốc, Myanmar, Ấn Độ, Bangladesh, Sri Lanka, và Việt Nam. Ở Việt Nam, cây mọc hoang tại các tỉnh miền Bắc như Hà Tây (Ba Vì), Lai Châu, Thanh Hóa, Nghệ An và Hà Tĩnh. Theo y học cổ truyền, hoàng nàn có vị khổ, tính hàn, rất độc, quy vào kinh can và tỳ, với công năng trừ phong hàn thấp tý, chỉ thông, chỉ tả, và sát trùng. Dược liệu này được dùng để trị các bệnh đau nhức xương cốt, đau bụng, tiêu chảy, và ghẻ ngứa, nhưng cần chế biến kỹ để giảm độc tính. Thành phần hóa học chính của hoàng nàn là nhóm alkaloid (chiếm khoảng 9%), bao gồm strychnin, brucin, colubrin, maracurin, và pseudo-strychnin. Các hoạt chất này có tác dụng kích thích hệ thần kinh trung ương, kích thích tiêu hóa, giảm đau, hỗ trợ điều trị tê liệt và suy nhược thần kinh. Có tác dụng dược lý như cải thiện tình trạng suy nhược thần kinh, cải thiện tình trạng suy nhược thần kinh.

:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Hoàng Nàn - Vỏ Thân, Vỏ Cành
- Dược liệu tiếng Trung: nan (nan)
- Dược liệu tiếng Anh: nan
- Dược liệu latin thông dụng: Cortex Strychni Wallichianae
- Dược liệu latin kiểu DĐVN: *Fructus Amomum Tsao-ko*
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Vỏ Thân, Vỏ Cành (Cortex)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** nan 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: nan 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Hoàng Nàn - Vỏ Thân, Vỏ Cành** từ bộ phận **Vỏ Thân, Vỏ Cành** từ loài *Strychnos wallichiana*.

**Mô tả thực vật:** Hoàng nàn là một loại cây mọc leo, cành gầy, nhẵn, có những móc mọc đối ở đầu những cành non, thân có vỏ xám, với những đám màu vàng đỏ. Lá mọc đối, nhẵn, dai, hơi bầu dục, phía cuống nhọn hay hơi tròn, đầu tù hay nhọn, dài 6-12cm, rộng 3-6cm, cuống ngắn. Hoa không cuống, mọc thành chùy ngù tận cùng, phủ lông màu hung nâu. Quả hình cầu, đường kính 4-5cm, vỏ ngoài cứng, dài 4mm, trong chứa nhiều hạt hình khuy áo, đường kính 22mm hay hơn, dày 18mm giống như hạt mã tiền, cho nên có người cho hoàng nàn là vỏ cây mã tiền. Thu hái hạt thì gọi là mã tiền, thu hái vỏ thì gọi là hoàng nàn.

*Tài liệu tham khảo:* "Những cây thuốc và vị thuốc Việt Nam" - Đỗ Tất Lợi 
Trong dược điển Việt nam, loài *Strychnos wallichiana* được sử dụng làm dược liệu. 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  Chứa 9% alcaloid toàn phần gồm colubrin, strychnin, brucin, maracurin và pseudo strychnin.
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: nan

---

## V. Dược điển Việt Nam V

### Soi bột

nan

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

nan

### Định lượng

nan

### Thông tin khác 

- **Độ ẩm:** nan
- **Bảo quản:** nan

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** nan

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** nan 


:::


::: {#listing-ViThuoc}
:::

