---
title: Fructus Chaenomelis
subtitle: Mộc Qua - Quả
description: "Dược liệu Mộc Qua - Quả từ Quả Chín của loài *Chaenomeles speciosa* thuộc Họ Asteraceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: https://medialib.naturalis.nl/file/id/U.1145389/format/large
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Fructus Chaenomelis/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Fructus Chaenomelis/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Fructus Chaenomelis/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Fructus Chaenomelis/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Asteraceae
tags: [Chaenomeles speciosa, Asteraceae]
---

::: {.callout-note title = "Tóm tắt"}

Mộc qua có tên khoa học là Chaenomeles speciosa (Sweet) Nakai, bộ phận sử dụng làm thuốc là quả. Đây là loài cây bản địa của Trung Quốc và được di thực đến nhiều nơi trên thế giới. Theo y học cổ truyền, mộc qua được dùng làm thuốc chữa đau nhức thắt lưng, đầu gối, thấp khớp, ho lâu ngày, gân mạch co rút, chuột rút. Mộc qua có tác dụng giảm đau, chống viêm, ngoài ra còn giúp bổ sung vitamin C, B1. Thành phần hóa học chủ yếu của quả mộc qua gồm có Flavonoid, Monosaccharide (glucose, fructose) và các acid hữu cơ (acid citric, acid malic, acid tartaric).

:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Mộc Qua - Quả
- Dược liệu tiếng Trung: ? (?)
- Dược liệu tiếng Anh: ?
- Dược liệu latin thông dụng: Fructus Chaenomelis
- Dược liệu latin kiểu DĐVN: *Frucius Chaenomelisn*
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Quả Chín (Frucius)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** Quả thuôn dài, bổ dọc thành hai nửa đối nhau, dài 4 cm đến 9 cm, rộng 2 cm đến 5 cm, dày 1 cm đến 2,5 cm. Mặt  ngoài màu đỏ tía hoặc nâu đỏ, có nếp nhăn sâu, không đều;  mép mặt bổ cong vào phía trong, cùi quả màu nâu đỏ, phân  giữa lõm xuống, màu vàng nâu. Hạt dẹt hình tam giác dài,  thường rơi ra ngoài; mặt ngoài hạt nhẵn bóng. Chất cứng, mùi thơm nhẹ, vị chua, hơi chát. 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: Thu hoạch vào mùa hạ hoặc mùa thu. Hái lấy quả màu  vàng hơi xanh lục, luộc đến khi vỏ ngoài chuyển thành  màu trắng hơi xám, vớt ra bổ đôi dọc quả và phơi khô. nn 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Mộc Qua - Quả** từ bộ phận **Quả Chín** từ loài *Chaenomeles speciosa*.

**Mô tả thực vật:** Mộc qua là một cây nhỡ cao 2-3m, cành có gai, dài 5-20mm, đường kính phía gốc của gai tới 1-3mm, mặt cành có những bì không rõ. Lá có cuống dài 3-15mm, phiến lá hình mác dài 2.5cm-11cm, rộng 1,5cm-4cm mép có răng cưa. mặt trên màu xanh, mặt dưới màu tím nhạt, cả hai mặt đều nhẫn. Lá kèm có hình dạng và kích thước thay đổi, dài từ 2-2,5cm, rộng từ 1-1,5cm. mép cũng có răng cưa. Hoa mọc thành chùm ở kẽ lá. Cánh hoa màu đỏ của hoa đào, có loại hoa trắng hay hồng. Cuống hoa rất ngắn. Quả thịt hình cầu hay hình trứng, dài khoảng 8 cm, mặt ngoài nhẵn bóng, màu vàng hay vàng xanh, mùi thơm. Mùa hoa: tháng 3-4, mùa quả: tháng 9-10.

*Tài liệu tham khảo:* "Những cây thuốc và vị thuốc Việt Nam" - Đỗ Tất Lợi 
Trong dược điển Việt nam, loài *Chaenomeles speciosa* được sử dụng làm dược liệu. 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  (1) Nhóm hóa học: Trong mộc qua có Flavonoid, Monosaccharide (glucose, fructose), acid hữu cơ (acid citric, acid malic, acid tartaric)
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: nan

---

## V. Dược điển Việt Nam V

### Soi bột

Bột màu nâu tía. Soi kinh hiển vi thấy: Mảnh biểu bì tế bào  hình chữ nhật. Mảnh mô mềm gồm các tế bào hình nhiều cạnh, rải rác có tế bào mô cứng đứng riêng hay họp thành  từng đám, màu vàng, hình trái xoan, thành dày, có ống trao  đồi rõ. Mảnh mạch mạng. Tinh thể calci oxalat hình khối  chữ nhật.

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

A.Lấy 1 g bột dược liệu, thêm 10 ml ethanol 70 % (TT), đun hồi lưu trên cách thủy 1 h, lọc, được dịch lọc A dùng  để làm các phản ứng sau: Lấy 2 ml dịch lọc A, bốc hơi trên cách thủy đến cắn khô,  thêm 1 ml anhydrid acetic (TT) và 1 ml  cloroform (TT),  khuấy kỹ và lọc vào một ống nghiệm khô. Cho thận trọng  dọc theo thành ống nghiệm khoảng 1 ml acid sulfuric (TT),  ở giữa hai lớp dung dịch sẽ xuất hiện vòng màu đỏ tím, lớp  dung dịch phía trên có màu xanh lục. Nhỏ vài giọt dịch lọc A lên một miếng giấy lọc, để khô rồi  quan sát dưới ánh sáng tử ngoại ở bước sóng 366 nm sẽ  thấy vết huỳnh quang xanh nhạt sáng. Nhỏ chồng lên vết dịch lọc này 1 giọt đến 2 giọt dung dịch  nhôm clorid 1% trong methanol (TT), để khô rồi quan sát  dưới ánh sáng tử ngoại ở bước sóng 366 nm sẽ thấy vết  huỳnh quang xanh lục sáng. B. Phương pháp sắc ký lớp mỏng (Phụ lục 5.4). Bản mỏng: Silica gel G. Dung môi khai triển: Ethyl acetat –  acid formic – nước  (8: 1,5:1). Dung dịch thử: Lấy khoảng 1 ml dịch lọc A, cô trên cách  thủy đến cắn khô, thêm vào cắn 1 ml methanol (TT). Dung dịch đối chiếu: Dùng 1 g bột Mộc qua (mẫu chuẩn),  chiết như mô tả ở phần Dung dịch thử. Cách tiến hành: Chấm riêng biệt bản mỏng lên 10 µl mỗi  dung dịch trên. Sau khi triển khai xong, lấy bản mỏng ra,  để khô ngoài không khí. Phun dung dịch nhôm clorid 1 %  trong methanol (TT). Để khô bản mỏng và quan sát dưới  ánh sáng tử ngoại ở bước sóng 366 nm. Trên sắc ký đồ của  dung dịch thử phải cho các vết cùng màu và cùng gíá trị Rf  vói các vết trên sắc ký đồ của dung dịch đối chiếu.

### Định lượng

Chất chiết được trong dược liệu Không ít hơn 15,0 % tính theo dược liệu khô kiệt. Tiến hành theo phương pháp chiết nóng (Phụ lục 12.10).  Dùng ethanol 96 % (TT) làm dung môi.

### Thông tin khác 

- **Độ ẩm:** Không quá 12,0 % (Phụ lục 9.6, 1 g, 105  °C, 4 h).
- **Bảo quản:** nan

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** Toan, ôn. Vào các kinh tỳ, vị, can, phế.

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** nan 


:::


::: {#listing-ViThuoc}
:::

