---
title: Fructus Zanthoxyli
subtitle: Xuyên Tiêu - Quả
description: "Dược liệu Xuyên Tiêu - Quả từ Quả của loài *Zanthoxylum sp.* thuộc Họ Apiaceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: http://mediaphoto.mnhn.fr/media/1441337711135BJDFu2HvGkSSesAd
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Fructus Zanthoxyli/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Fructus Zanthoxyli/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Fructus Zanthoxyli/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Fructus Zanthoxyli/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Apiaceae
tags: [Zanthoxylum sp., Apiaceae]
---

::: {.callout-note title = "Tóm tắt"}

Quả xuyên tiêu (Fructus Zanthoxyli) là quả đã phơi khô của nhiều loài Xuyên tiêu (Zanhoxylum sp.), thuộc họ Cam(Rutaceae). Cây mọc hoang ở các tỉnh miền Bắc và Trung Việt Nam. Theo tài liệu cổ, quả xuyên tiêu có tính tân, ôn, vào ba kinh: phế, tỳ, thận. Dược liệu dùng trị đau bụng lạnh, nôn mửa, ỉa chảy, phong thấp, đau răng, đau bụng giun. Các thành phần hóa học chính của quả xuyên tiêu bao gồm tinh dầu (geraniol, limonene, cumic alcohol), alkaloids và flavonoids.


:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Xuyên Tiêu - Quả
- Dược liệu tiếng Trung: nan (nan)
- Dược liệu tiếng Anh: nan
- Dược liệu latin thông dụng: Fructus Zanthoxyli
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Quả (Fructus)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** nan 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: nan 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Xuyên Tiêu - Quả** từ bộ phận **Quả** từ loài *Zanthoxylum sp.*.

**Mô tả thực vật:** Quả nhỏ, khô, thường tập trung từ 1 dến 3 hoặc 5 quà
trên một cuống chùm quá, xếp thành hình sao. Quả nang,
đường kính 3 mm đến 5 mm, khi chín nứt thành hai mảnh
vò, mặt ngoài màu nâu xám, cỏ nhiều điểm tinh dầu và vân
sần sùi hình mạng; mặt trong màu tráng xám, nhẵn bóng.
Hạt hình trứng, đường kính 2 mm đen 3 mm, màu đen,
nhẵn bóng. Mùi thơm, vị cay tè lưỡi.

*Tài liệu tham khảo:* Tài liệu khác 
Trong dược điển Việt nam, loài *Zanthoxylum sp.* được sử dụng làm dược liệu. 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  "(1) Nhóm hóa học: Tinh dầu: Các hợp chất dễ bay hơi, bao gồm Geraniol, Limonene, và Cumic alcohol."
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: nan

---

## V. Dược điển Việt Nam V

### Soi bột

nan

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

nan

### Định lượng

nan

### Thông tin khác 

- **Độ ẩm:** nan
- **Bảo quản:** nan

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** nan

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** nan 


:::


::: {#listing-ViThuoc}
:::

