---
title: Herba Elsholtziae Ciliatae
subtitle: Kinh Giới - Thân Cây Trên Mặt Đất
description: "Dược liệu Kinh Giới - Thân Cây Trên Mặt Đất từ Thân Cây Trên Mặt Đất của loài *Elsholtzia ciliata* thuộc Họ Caprifoliaceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: https://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=e09cc963-6f68-4209-8341-3d303194ddf4
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Herba Elsholtziae Ciliatae/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Herba Elsholtziae Ciliatae/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Herba Elsholtziae Ciliatae/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Herba Elsholtziae Ciliatae/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Caprifoliaceae
tags: [Elsholtzia ciliata, Caprifoliaceae]
---

::: {.callout-note title = "Tóm tắt"}

Kinh giới (Herba Elsholtziae) là toàn cây trên mặt đất của cây kinh giới (Elsholtzia ciliata (Thunb.) Hyland), thuộc họ Hoa môi (Lamiaceae). Kinh giới phân bố chủ yếu ở châu Á, bao gồm khu vực bán đảo Malaysia và vùng ôn đới châu Á. Ở Việt Nam, cây được trồng khắp nơi, đặc biệt tại các tỉnh như Lào Cai, Cao Bằng, Lạng Sơn, Phú Thọ, Vĩnh Phúc, Hoà Bình, Hà Nội, Ninh Bình và các tỉnh phía Nam. Theo tài liệu cổ, kinh giới có vị cay, tính ấm, quy vào kinh phế và can, được dùng để chữa cảm mạo, phát sốt, nhức đầu, cổ họng sưng đau, nôn mửa, chảy máu cam, đi lỵ ra máu, và băng huyết. Kinh giới có tác dụng dược lý kháng khuẩn, chống viêm, chống oxy hóa, giảm căng thẳng, an thần, và hỗ trợ tiêu hóa. Kinh giới chứa các thành phần hóa học quan trọng như tinh dầu giàu phytosterol (stigmast-5-en-3-ol), flavonoid (luteolin), và terpenoid (terpineol, limonene, alpha-pinene, humulene, camphor, sabinene).



:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Kinh Giới - Thân Cây Trên Mặt Đất
- Dược liệu tiếng Trung: nan (nan)
- Dược liệu tiếng Anh: nan
- Dược liệu latin thông dụng: Herba Elsholtziae Ciliatae
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Thân Cây Trên Mặt Đất (Herba)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** nan 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: nan 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Kinh Giới - Thân Cây Trên Mặt Đất** từ bộ phận **Thân Cây Trên Mặt Đất** từ loài *Elsholtzia ciliata*.

**Mô tả thực vật:** Cây kinh giới nhân dân ta vẫn trống để ăn làm gia vị và làm thuốc đã được xác định là Elsholtzia cristata. Cây thuộc thảo, cao 0,30-0,45m, thân nhẵn, mọc thẳng đứng. Lá mọc đối, phiến lá thuôn nhọn, dài 5-8cm, rộng 3cm, mép có răng cưa, cuống gây dài 2-3cm. Hoa nhỏ, không cuống, màu tím nhạt, mọc thành vòng ở đầu cành, rất mau. Quả gồm 4 hạch nhỏ, nhẵn, dài 0,5cm.

*Tài liệu tham khảo:* "Những cây thuốc và vị thuốc Việt Nam" - Đỗ Tất Lợi 
Trong dược điển Việt nam, loài *Elsholtzia ciliata* được sử dụng làm dược liệu. 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  (1) Nhóm hóa học:
Nhóm phytosterol: Stigmast-5-en-3-ol, (3β), Stigmast-5-en-3-ol, nerolidol
Flavonoid: Luteolin
Terpenoids: Terpineol, Limonene,Ursolic acid, Alpha-pinene, Humulene, Camphor, Sabinene, Carveol
(2) Trong dược điển Việt Nam không có thông tin định tính và định lượng
Theo Dược điển Đài Loan (Jing jie): pulegone
Thử nghiệm nhận dạng sắc ký lớp mỏng :
1. Dung dịch mẫu: Thêm 1,0 g mẫu dạng bột vào 10 mL methanol, siêu âm trong 15 phút, ly tâm trong 10 phút, lọc, bốc hơi phần dịch trong đến khô và hòa tan phần cặn trong 1 mL methanol.
2. Dung dịch thuốc đối chiếu: Dùng 1,0 g thuốc đối chiếu theo phương pháp tương tự như trên
3. Dung dịch chuẩn tham chiếu: Cân chính xác một lượng pulegone và hòa tan trong ete dầu hỏa (30-60°C) để tạo ra dung dịch chứa 1 µL mg trên ml.
4. Quy trình: Sử dụng silica gel Fas4 làm chất phủ và dung dịch n-hexan và etyl axetat (17:3) làm dung môi hiện ảnh. Thoa 2 ul dung dịch mẫu và dung dịch thuốc đối chiếu và 1 µL dung dịch chuẩn đối chiếu lên bản mỏng. Khi phần trên của dung môi dâng lên khoảng 5-10 cm so với gốc, để khô trong không khí. Phun dung dịch p-Anisaldehyd-H:SO, TS và đun nóng ở 105 C cho đến khi các vết hiện rõ, quan sát dưới ánh sáng khả kiến. Các vết trong sắc ký đồ thu được từ dung dịch mẫu tương ứng về giá trị R và màu với các vết trong sắc ký đồ thu được từ dung dịch thuốc đối chiếu và dung dịch chuẩn đối chiếu
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: nan

---

## V. Dược điển Việt Nam V

### Soi bột

nan

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

nan

### Định lượng

nan

### Thông tin khác 

- **Độ ẩm:** nan
- **Bảo quản:** nan

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** nan

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** nan 


:::


::: {#listing-ViThuoc}
:::

