---
title: Rhizoma Anemarrhenae
subtitle: Tri Mẫu - Thân Rễ
description: "Dược liệu Tri Mẫu - Thân Rễ từ Thân Rễ của loài *Anemarrhena asphodeloides* thuộc Họ Apiaceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: http://n2t.net/ark:/65665/m3f2f7e5f5-c9b4-46d7-94f8-a2a2b619a00b
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Rhizoma Anemarrhenae/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Rhizoma Anemarrhenae/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Rhizoma Anemarrhenae/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Rhizoma Anemarrhenae/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Apiaceae
tags: [Anemarrhena asphodeloides, Apiaceae]
---

::: {.callout-note title = "Tóm tắt"}

Tri mẫu (Rhizoma Anemarrhenae) là phần thân rễ phơi hoặc sấy khô của cây Tri mẫu (Anemarrhena asphodeloides Bunge), thuộc họ Hành (Liliaceae). Loài dược liệu này có nguồn gốc từ Trung Quốc. Theo tài liệu cổ, tri mẫu có vị đắng, tính lạnh, không độc, có tác dụng tu thân, bổ thủy, tả hỏa, thường được dùng để chữa bệnh tiêu khát (đái đường), hạ thủy, ích khí. Tác dụng dược lý của tri mẫu bao gồm bảo vệ thần kinh, tác dụng lên hệ máu, chống khối u, và chống viêm. Thành phần hóa học của tri mẫu chứa một chất saponin gọi là asphonin, ngoài ra còn có các steroid, coumarins và flavonoid.

:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Tri Mẫu - Thân Rễ
- Dược liệu tiếng Trung: nan (nan)
- Dược liệu tiếng Anh: nan
- Dược liệu latin thông dụng: Rhizoma Anemarrhenae
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Thân Rễ (Rhizoma)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** nan 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: nan 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Tri Mẫu - Thân Rễ** từ bộ phận **Thân Rễ** từ loài *Anemarrhena asphodeloides*.

**Mô tả thực vật:** Tri mẫu là một loại cỏ sống lâu năm, thân rễ chạy ngang. Lá mọc vòng, dài khoảng 20-30cm, hẹp, đầu nhọn, phía dưới ôm vào nhau. Mùa hạ, ra cành mang hoa. Cao chừng 60-90cm. Cụm hoa thành bông hoa nhỏ, màu trắng.

*Tài liệu tham khảo:* "Những cây thuốc và vị thuốc Việt Nam" - Đỗ Tất Lợi 
Trong dược điển Việt nam, loài *Anemarrhena asphodeloides* được sử dụng làm dược liệu. 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  Thành phần hoá học

Trong tri mẫu có một chất saponin gọi là asphonin. Ngoài ra còn một chất có tinh thể chưa xác định.
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: nan

---

## V. Dược điển Việt Nam V

### Soi bột

nan

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

nan

### Định lượng

nan

### Thông tin khác 

- **Độ ẩm:** nan
- **Bảo quản:** nan

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** nan

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** nan 


:::


::: {#listing-ViThuoc}
:::

