---
title: Rhizoma Polygonati
subtitle: Hoàng Tinh - Thân Rễ
description: "Dược liệu Hoàng Tinh - Thân Rễ từ Thân Rễ của loài *Polygonatum kingianum,  Polygonatum,  Polygonatum* thuộc Họ Ranunculaceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: http://n2t.net/ark:/65665/m3c821e52b-b2ba-42af-89a1-0d3b9d748265
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Rhizoma Polygonati/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Rhizoma Polygonati/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Rhizoma Polygonati/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Rhizoma Polygonati/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Ranunculaceae
tags: [ Polygonatum, Ranunculaceae]
---

::: {.callout-note title = "Tóm tắt"}

Thân rễ hoàng tinh (Polygonatum kingianum Coll. et Hemsl) thuộc họ Mạch môn đông (Convallariaceae). Cây mọc hoang tại các rừng ẩm ở miền Bắc Việt Nam, đặc biệt ở Sapa, và phân bố tại Trung Quốc, Myanmar, Thái Lan. Đây là loại cỏ sống lâu năm, thân rễ phát triển thành củ mập, màu vàng trắng, thân mọc thẳng, lá không cuống, hoa tím đỏ, quả mọng màu đen khi chín. Thành phần hóa học của hoàng tinh bao gồm chất nhầy, tinh bột, đường và các hợp chất có phản ứng dương tính với thuốc thử alkaloid. Trong y học cổ truyền, hoàng tinh được sử dụng để bổ khí huyết, tăng cường sức khỏe, dưỡng âm bổ phế, hỗ trợ tiêu hóa, hạ đường huyết, cải thiện trí nhớ và tăng cường hệ thần kinh, cũng như kháng viêm và chống lão hóa. Đây là một vị thuốc bổ dưỡng nhưng cần được sử dụng đúng cách để phát huy hiệu quả.

:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Hoàng Tinh - Thân Rễ
- Dược liệu tiếng Trung: nan (nan)
- Dược liệu tiếng Anh: nan
- Dược liệu latin thông dụng: Rhizoma Polygonati
- Dược liệu latin kiểu DĐVN: *Calyx Kaki*
- Dược liệu latin kiểu DĐVN: *nan*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Thân Rễ (Rhizoma)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** nan 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: nan 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Hoàng Tinh - Thân Rễ** từ bộ phận **Thân Rễ** từ loài *Polygonatum kingianum*.

**Mô tả thực vật:** Cây loại cỏ sống lâu năm, thân rễ mọc ngang, có khi phân nhánh, mẫm lên thành củ màu vàng trắng, hơi dẹt nên có sẹo lõm là vét thân còn sót lại, đường kính vết thân có thể đạt tới 2cm. Chiều dài củ có thể tới 30-35cm, rộng tới 6-7cm và dày tới 2-3cm. Thân mọc đứng nhẵn bóng, cao 50-80cm. Lá không cuống mọc vòng ytong 4-5 lá một. Phiến lá hình mác dài 7-12cm, rộng 5-12mm, đầu lá nhọn và quăn. Hoa mọc ở kẽ lá rũ xuống; cuống hoa dài 1,5-2cm, mỗi cuống mang hình ống dài 8-15mm màu tím đỏ. Mùa hoa ở Sapa (Lào Cai) vào tháng 3-4. Quả mọng, hình cầu đường kính 7-10mm, khi chín có màu đen

*Tài liệu tham khảo:* "Những cây thuốc và vị thuốc Việt Nam" - Đỗ Tất Lợi 
Trong dược điển Việt nam, một số loài có thể dùng thay thế cho nhau làm dược liệu bao gồm *Polygonatum kingianum,  Polygonatum,  Polygonatum* 
Chưa có thông tin về loài này trên gibf
 
Chưa có thông tin về loài này trên gibf
 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  Chưa rõ hoạt chất là gì. Chỉ mới biết trong củ hoàng tinh có chất nhầy, tinh bột và đường. Dịch chiết bằng ete từ củ hoàng tinh cho với các thuốc thử ancaloit phản ứng dương tính
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: nan

---

## V. Dược điển Việt Nam V

### Soi bột

nan

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

nan

### Định lượng

nan

### Thông tin khác 

- **Độ ẩm:** nan
- **Bảo quản:** nan

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** nan

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** nan 


:::


::: {#listing-ViThuoc}
:::

