---
title: Tuber Corydalis
subtitle: Diên Hổ Sách - Thân Rễ
description: "Dược liệu Diên Hổ Sách - Thân Rễ từ Thân Rễ của loài *Corydalis yanhusuo* thuộc Họ Polypodiaceae."
author: "TS. Hoàng Lê Sơn"
toc: true
image: http://mediaphoto.mnhn.fr/media/1452860566278VU3jBVIGfplZ9A5p
title-block-banner: true
format: 
  html: 
    code-fold: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    lightbox: true
lightbox: auto
fig-cap-location: top
listing:
  - id: listing-soibot
    template: gallery.ejs
    contents: "Tuber Corydalis/Soi_Bot/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-viphau
    template: gallery.ejs
    contents: "Tuber Corydalis/Vi_Phau/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-DDHK
    template: gallery_pdf.ejs
    contents: "Tuber Corydalis/DDHK/*.*"
    sort-ui: false
    filter-ui: false
    categories: false

  - id: listing-ViThuoc
    template: gallery.ejs
    contents: "Tuber Corydalis/Vi_Thuoc/*.*"
    sort-ui: false
    filter-ui: false
    categories: false
categories: Polypodiaceae
tags: [Corydalis yanhusuo, Polypodiaceae]
---

::: {.callout-note title = "Tóm tắt"}

nan

:::


## I. Thông tin về dược liệu 

::: {.panel-tabset}

### Định danh

- Dược liệu tiếng Việt: Diên Hổ Sách - Thân Rễ
- Dược liệu tiếng Trung: 延胡索 (Yan Hu Suo)
- Dược liệu tiếng Anh: Corydalis Tuber
- Dược liệu latin thông dụng: Tuber Corydalis
- Dược liệu latin kiểu DĐVN: *Pericarpium Garciniae Mangostanae*
- Dược liệu latin kiểu DĐVN: *Corydalis Rhizoma*
- Dược liệu latin kiểu thông tư: *nan*
- Bộ phận dùng: Thân Rễ (Tuber)

### Mô tả dược liệu 

**Theo dược điển Việt nam V:** Rễ củ hình cầu dẹt không đều, đường kính 0,5 cm đến 1,5 cm. Mặt ngoài màu vàng hay vàng nâu, có vân nhăn hình mạng lưới không đều. Đỉnh có vết sẹo, thân hơi lõm, đáy thường lồi lên. Chất cứng, giòn. Mặt cắt ngang màu vàng, cứng như sừng, sáng bóng như sáp. Mùi nhẹ, vị đắng. 
 
**Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** nan

### Chế biến 

**Chế biến theo dược điển việt nam V**: Thu hoạch vào đầu mùa hạ khi cây khô héo. Đào lấy rễ, loại bỏ rễ con, thân và lá, rửa sạch, luộc đến khi cắt ngang không còn lõi màu trắng và phơi hoặc sấy nhẹ đến khô.Bào chế Diên hồ sách sống: Lấy diên hồ sách đã chế biến, loại bỏ tạp chất, rửa sạch, để khô, thái lát dày hoặc đập vụn trước khi dùng. Thố Diên hồ sách (chế dấm): Cho dấm vào diên hồ sách sạch đã thái lát hoặc đập vụn, trộn đều, ủ cho thấm đều dấm cho vào chảo, sao nhỏ lửa đến khô. Hoặc luộc với dấm: Lấy diên hồ sách đã chế biến, thêm dấm, đun nhỏ lửa cho đến khi dấm thấm hết vào thuốc, để nguội, thái phiến dày phơi hoặc sấy nhẹ đến khô, hoặc khi dùng giã nát.Dùng 2l dấm cho 10 kg dược liệu. 

**Chế biến theo thông tư:** nan

::: 


## II. Thông tin về thực vật


Dược liệu **Diên Hổ Sách - Thân Rễ** từ bộ phận **Thân Rễ** từ loài *Corydalis yanhusuo*.

**Mô tả thực vật:** nan

*Tài liệu tham khảo:* nan 
Trong dược điển Việt nam, loài *Corydalis yanhusuo* được sử dụng làm dược liệu. 
Chưa có thông tin về loài này trên gibf


## III. Thành phần hóa học

Theo tài liệu của GS. Đỗ Tất Lợi:  nan
    
Chưa có nghiên cứu về thành phần hóa học trên cơ sở Lotus

---

## IV. Tác dụng dược lý

Theo tài liệu quốc tế: 1. To invigorate blood and promote qi circulation; 2. To stop pain

---

## V. Dược điển Việt Nam V

### Soi bột

Màu lục vàng, hạt tinh bột đã hồ hóa thành từng khối màu vàng nhạt hoặc không màu. Mô cứng của nội bì màu vàng lục gồm các tế bào hình nhiều cạnh, gần vuông hoặc bầu dục, thuôn dài, thành tế bào hơi lượn sóng, hóa gỗ, có các lỗ nhỏ dày đặc. Tế bào đá màu vàng nhạt, hình gần tròn hay thuôn dài, đường kính tới 60 pm, thành tương đối dày có các lỗ nhỏ dày đặc. Mạch xoắn đường kính 16 pm đến 32 pm.

::: {#listing-soibot}
:::

### Vi phẫu

nan

::: {#listing-viphau}
:::

### Định tính

Phương pháp sắc ký lớp mỏng (Phụ lục 5.4). Bản mỏng: Silica gel G, dùng dung dịch natri hydroxyd (TT) 1 % để tráng bản mỏng. Dung môi khai triển: n-hexan – cloroform – methanol (7,5 :4 : 1).nDung dịch thử: Cho 1 g bột dược liệu vào một bình cầu, thêm 50 ml ethanol 96 % (TT), đun hồi lưu trên cách thủy 1 h. Để nguội, lọc, bốc hơi dịch lọc đến khô trên cách thủy, Hòa tan cắn trong 10 ml nước, kiềm hóa bằng amoniac đậm đặc (TT), chiết bằng ether (TT) 3 lần, mỗi lần 10 ml. Gộp các dịch chiết ether, bốc hơi đến cắn khô trên cách thủy. Hòa tan cắn trong 1 ml methanol (TT) được dung dịch thử. Dung dịch chất đối chiếu: Hòa tan tetrahydropalmatin chuẩn trong methanol (TT) để được dung dịch có nồng độ 1 mg/ml.nDung dịch dược liệu đối chiếu: Nếu không có tetrahydropalmatin có thể dùng 1 g bột Diên hồ sách (mẫu chuẩn), chiết như mô tả ờ phần dung dịch thử. Cách tiến hành: Chấm riêng biệt lên bản mỏng 5 µl mỗi dung dịch trên. Sau khi triển khai xong, lấy bản mỏng ra, để khô ngoài không khí. Phun thuốc thử Dragendorff (TT). Quan sát dưới ánh sáng thường. Trên sắc ký đồ của dung dịch thử phải có vết cùng màu sắc và giá trị Rf với vết tetrahydropalmatin trên sắc ký đồ của dung dịch chất đối chiếu hoặc phải có các vết cùng màu sắc và giá trị Rf với các vết trên sắc ký đồ của dung dịch dược liệu đối chiếu.

### Định lượng

Chất chiết được trong dươc liệu Không dưới 13,0 % tính theo dược liệu khô kiệt. Tiến hành theo phương pháp chiết nóng (Phụ lục 12.10). Dùng ethanol 50 % (TT) làm dung môi.

### Thông tin khác 

- **Độ ẩm:** Không quá 15 % (Phụ lục 9.6, 1 g, 105 °c, 5 h).
- **Bảo quản:** Nơi khô ráo, tránh mốc mọt.

## VI. Dược điển Hồng kong

::: {#listing-DDHK}
:::


---

## VII. Y dược học cổ truyền

::: {.callout-note title = "nan" }

**Tên vị thuốc:** nan

**Tính:** nan

**Vị:** nan

**Quy kinh:**  nan

**Công năng chủ trị:** Tân, khổ, ôn. Vào các kinh Can, phế, tỳ.

**Phân loại theo thông tư:** nan

**Tác dụng theo y dược cổ truyền:** nan

**Chú ý:** nan

**Kiêng kỵ:** Không dùng cho phụ nữ có thai, người huyết hư, phụ nữ rối loạn kinh nguyệt. 


:::


::: {#listing-ViThuoc}
:::

